/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 ../public/nesDraco.gltf
Author: Fabián Torres (https://sketchfab.com/fabienstone)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nes-controller-cb799f21731a4aa48271dd72949fc9fe
Title: NES Controller
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/nesDraco.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.12} rotation={[Math.PI / 4.5 , 0, 0]}>
        <mesh
          geometry={nodes["controller_low_backup_nes-controller_0"].geometry}
          material={materials["backup_nes-controller"]}
          position={[11.658, 3.675, 6.032]}
          rotation={[-Math.PI / 3, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes["button-b_low_backup_nes-controller_0"].geometry}
          material={materials["backup_nes-controller"]}
          position={[38.692, 5.785, 20.876]}
          rotation={[-Math.PI / 3, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes["button-a_low_backup_nes-controller_0"].geometry}
          material={materials["backup_nes-controller"]}
          position={[55.779, 5.785, 20.876]}
          rotation={[-Math.PI / 3, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes["button-cross_low_backup_nes-controller_0"].geometry}
          material={materials["backup_nes-controller"]}
          position={[-30.792, 8.773, 15.14]}
          rotation={[-Math.PI / 3, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={
            nodes["buttons-select-start_low_backup_nes-controller_0"].geometry
          }
          material={materials["backup_nes-controller"]}
          position={[7.187, 5.688, 20.901]}
          rotation={[-Math.PI / 3, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/nesDraco.gltf");
